name: yarn generate

on:
  push:
  workflow_dispatch:
  schedule: 
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        id: checkout
        name: git checkout
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: 20
        id: setup-node
        name: nvm use node 20
      - run: npm i -g yarn
        id: setup-yarn
        name: npm i yarn
      - run: yarn --frozen-lockfile
        id: install-deps
        name: yarn install
      - run: yarn generate
        id: generate-readme
        name: yarn generate
      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        id: format-files
        name: git commit
        with:
          commit_message: "docs: generate readme"
          skip_checkout: true
          branch: "docs-generate-${{ github.sha }}"
          create_branch: true
      - if: steps.format-files.outputs.changes_detected == 'true'
        id: create-pr
        name: gh pr create
        run: git checkout docs-generate-${{ github.sha }} && gh pr create --base main --head docs-generate-${{ github.sha }} --title 'Merge generated files into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.format-files.outputs.changes_detected == 'true'
        id: merge-pr
        name: gh pr merge
        run: gh pr merge --admin --merge --subject 'Merge generated docs' --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
